export const burgerConstants = {
  BURGER_LIST_REQUEST: 'BURGER_LIST_REQUEST',
  BURGER_LIST_REQUEST_SUCCESS: 'BURGER_LIST_REQUEST_SUCCESS',
  BURGER_LIST_REQUEST_FAILURE: 'BURGER_LIST_REQUEST_FAILURE',
  };
